#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Laravel\Lumen\Application;
use Laravel\Lumen\Console\Kernel;
use Illuminate\Console\Scheduling\Schedule;

$app = require __DIR__.'/backend/bootstrap.php';

$app->singleton(
    \Illuminate\Contracts\Console\Kernel::class,
    function()use($app){
        return new class($app) extends Kernel{
           public $commands = [
           ];
           /**
            * Define the application's command schedule.
            *
            * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
            * @return void
            */
           protected function schedule(Schedule $schedule)
           {
               //
           }
        };
    }
);

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
