#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require __DIR__.'/backend/bootstrap.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/
$app->singleton(
    \Illuminate\Contracts\Console\Kernel::class,
    function(){
        return new class($this->app) extends Kernel{
           /**
            * The Artisan commands provided by your application.
            *
            * @var array
            */
           public $commands = [
           ];
           /**
            * Define the application's command schedule.
            *
            * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
            * @return void
            */
           protected function schedule(Schedule $schedule)
           {
               //
           }
        };
    }
);



$app->extend(\Illuminate\Contracts\Console\Kernel::class,function($console){
    $console->addCommands([
        // your commands here
    ]);
    return $console;
});

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
